server:
  port: 10006
spring:
  application:
    name: hystrix-consumer
eureka:
  client:
    service-url:
      defaultZone: http://localhost:10001/eureka
management:
  endpoints:
    web:
      exposure:
        include:
          hystrix.stream,health,info
